=== diretto/JavaClientStoragePlugin/conf/org/diretto/api/client/main/storage/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="api-version" type="xs:string" />
				<xs:element name="service-class" type="xs:string" />
				<xs:element name="upload">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="max-parallel-uploads" type="xs:int" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="download">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="max-parallel-downloads" type="xs:int" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== diretto/JavaClientStoragePlugin/conf/org/diretto/api/client/main/storage/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

	<name>org.diretto.api.main.storage</name>
	<api-version>v2</api-version>
	<service-class>org.diretto.api.client.main.storage.StorageServiceImpl</service-class>
	
	<upload>
		<max-parallel-uploads>8</max-parallel-uploads>
	</upload>
	
	<download>
		<max-parallel-downloads>8</max-parallel-downloads>
	</download>
	
</config>
